#!/bin/bash
# script for Mount EFI 
# chris1111 

echo "==============================================="
echo "Post Post-Install Script"
echo "==============================================="

#echo "DEBUG: $ 1 = Full path to the installation package the installer app is processing: " $1
#echo "DEBUG: $ 2 = Full path to the installation destination: " $2
#echo "DEBUG: $ 3 = Installation volume (mountpoint) to receive the payload: " $3
#echo "DEBUG: $ 4 = Root directory for the system: " $4

echo "preinstall: Path to installer....... $1"
echo "preinstall: Path to destination..... $2"
echo "preinstall: Path to dest volume..... $3"
echo "preinstall: Root of system folder... $4"


#############################################################################

DEST_VOL="$3"
EFI_ROOT_DIR=$(cd "${DEST_VOL}"/Private/tmp/EFIROOTDIR; pwd -P)
Sleep 1
cp -rp /"${DEST_VOL}"/Private/tmp/EFI /"${DEST_VOL}"/Private/tmp/EFIROOTDIR
Sleep 1
./MYPatcher

# Remove link to the partition that contain the EFI folder
rm -rf "${DEST_VOL}"/Private/tmp/EFIROOTDIR
rm -rf "${DEST_VOL}"/Private/tmp/EFI


		