#!/bin/bash

if [ -d "${3}/Applications/MacEFIMounter.app" ]; then
    rm -rf "${3}/Applications/MacEFIMounter.app"
fi

if [ -d "${3}/Applications/IORegistryExplorer.app" ]; then
    rm -rf "${3}/Applications/IORegistryExplorer.app"
fi

if [ -d "${3}/Applications/MaciASL.app" ]; then
    rm -rf "${3}/Applications/MaciASL.app"
fi

if [ -d "${3}/Applications/OpenCore Configurator.app" ]; then
    rm -rf "${3}/Applications/OpenCore Configurator.app"
fi

if [ -d "${3}/Applications/Sleep-Finder.app" ]; then
    rm -rf "${3}/Applications/Sleep-Finder.app"
fi

if [ -d "${3}/Applications/RDM.app" ]; then
    rm -rf "${3}/Applications/RDM.app"
fi



tar xf /Private/tmp/Apps/IORegistryExplorer.zip --directory /Applications

tar xf /Private/tmp/Apps/"MacEFIMounter.zip" --directory /Applications

tar xf /Private/tmp/Apps/"Sleep-Finder.zip" --directory /Applications

tar xf /Private/tmp/Apps/MaciASL.zip --directory /Applications

tar xf /Private/tmp/Apps/OpenCoreConfigurator.zip --directory /Applications

tar xf /Private/tmp/Apps/RDM.zip --directory /Applications

Sleep 1
rm -rf /Private/tmp/Apps
Sleep 1


osascript <<EOD
  tell application "System Events"	get full name of current user	make new login item at end of login items with properties ¬		{path:"/Applications/MacEFIMounter.app"}end tell
EOD
