#!/bin/sh
# HP ProBook EliteBook Patcher  
# chris1111 

echo "==============================================="
echo "Post Post-Install Script"
echo "==============================================="

#echo "DEBUG: $ 1 = Full path to the installation package the installer app is processing: " $1
#echo "DEBUG: $ 2 = Full path to the installation destination: " $2
#echo "DEBUG: $ 3 = Installation volume (mountpoint) to receive the payload: " $3
#echo "DEBUG: $ 4 = Root directory for the system: " $4

echo "preinstall: Path to installer....... $1"
echo "preinstall: Path to destination..... $2"
echo "preinstall: Path to dest volume..... $3"
echo "preinstall: Root of system folder... $4"

echo "Remove install temp files"

if [ -d "${3}/tmp/EFI-DSDT" ]; then
	rm -rf "${3}/tmp/EFI-DSDT"
fi

if [ -d "${3}/tmp/Appli" ]; then
	rm -rf "${3}/tmp/Appli"
fi

rm -rf /"$3"/Private/tmp/EFI

exit