#!/bin/bash

if [ -d "${3}/Applications/Beta Access Software Utility.app" ]; then
    rm -rf "${3}/Applications/Beta Access Software Utility.app"
fi

if [ -d "${3}/Applications/Command Line EFI Mounteur.app" ]; then
    rm -rf "${3}/Applications/Command Line EFI Mounteur.app"
fi

if [ -d "${3}/Applications/Drop EFI.app" ]; then
    rm -rf "${3}/Applications/Drop EFI.app"
fi

if [ -d "${3}/Applications/Drop-EFI.app" ]; then
    rm -rf "${3}/Applications/Drop-EFI.app"
fi

if [ -d "${3}/Applications/IORegistryExplorer.app" ]; then
    rm -rf "${3}/Applications/IORegistryExplorer.app"
fi


if [ -d "${3}/Applications/MaciASL.app" ]; then
    rm -rf "${3}/Applications/MaciASL.app"
fi

if [ -d "${3}/Applications/OpenCore Configurator.app" ]; then
    rm -rf "${3}/Applications/OpenCore Configurator.app"
fi


if [ -d "${3}/Applications/RDM.app" ]; then
    rm -rf "${3}/Applications/RDM.app"
fi


tar xf /Private/tmp/Apps/Beta-Access-SoftwareUtility.zip --directory /Applications

tar xf /Private/tmp/Apps/IORegistryExplorer.zip --directory /Applications

tar xf /Private/tmp/Apps/CommandLineEFIMounter.zip --directory /Applications

tar xf /Private/tmp/Apps/"Drop-EFI.zip" --directory /Applications

tar xf /Private/tmp/Apps/MaciASL.zip --directory /Applications

tar xf /Private/tmp/Apps/OpenCoreConfigurator.zip --directory /Applications

tar xf /Private/tmp/Apps/RDM.zip --directory /Applications

cp -rf /Private/tmp/Apps/DropEFI.Agents.plist /Library/LaunchAgents
chown -R root:wheel /Library/LaunchAgents/DropEFI.Agents.plist
sleep 1
chmod -R 555 /Library/LaunchAgents/DropEFI.Agents.plist
# Load the new LaunchAgents.
/bin/launchctl load /Library/LaunchAgents/DropEFI.Agents.plist
Sleep 1
rm -rf /Private/tmp/Apps
Sleep 1
Open /Applications/"Drop-EFI.app"

