#!/bin/bash

if [ -d "${3}/Applications/Beta Access Software Utility.app" ]; then
    rm -rf "${3}/Applications/Beta Access Software Utility.app"
fi

if [ -d "${3}/Applications/Command Line EFI Mounter.app" ]; then
    rm -rf "${3}/Applications/Command Line EFI Mounter.app"
fi

if [ -d "${3}/Applications/Drop EFI.app" ]; then
    rm -rf "${3}/Applications/Drop EFI.app"
fi

if [ -d "${3}/Applications/Drop-EFI.app" ]; then
    rm -rf "${3}/Applications/Drop-EFI.app"
fi

if [ -d "${3}/Applications/IORegistryExplorer.app" ]; then
    rm -rf "${3}/Applications/IORegistryExplorer.app"
fi


if [ -d "${3}/Applications/MaciASL.app" ]; then
    rm -rf "${3}/Applications/MaciASL.app"
fi

if [ -d "${3}/Applications/OpenCore Configurator.app" ]; then
    rm -rf "${3}/Applications/OpenCore Configurator.app"
fi


if [ -d "${3}/Applications/RDM.app" ]; then
    rm -rf "${3}/Applications/RDM.app"
fi


tar xf /Private/tmp/Apps/Beta-Access-SoftwareUtility.zip --directory /Applications

tar xf /Private/tmp/Apps/IORegistryExplorer.zip --directory /Applications

tar xf /Private/tmp/Apps/CommandLineEFIMounter.zip --directory /Applications

tar xf /Private/tmp/Apps/"Drop-EFI.zip" --directory /Applications

tar xf /Private/tmp/Apps/MaciASL.zip --directory /Applications

tar xf /Private/tmp/Apps/OpenCoreConfigurator.zip --directory /Applications

tar xf /Private/tmp/Apps/RDM.zip --directory /Applications

Sleep 1
rm -rf /Private/tmp/Apps
Sleep 1

Open /Applications/"Drop-EFI.app"

osascript <<EOD
  tell application "System Events"	get full name of current user	make new login item at end of login items with properties ¬		{path:"/Applications/Drop-EFI.app"}end tell
EOD
