#!/bin/sh
# HP ProBook EliteBook Patcher  
# chris1111 

echo "==============================================="
echo "Post Post-Install Script"
echo "==============================================="

#echo "DEBUG: $ 1 = Full path to the installation package the installer app is processing: " $1
#echo "DEBUG: $ 2 = Full path to the installation destination: " $2
#echo "DEBUG: $ 3 = Installation volume (mountpoint) to receive the payload: " $3
#echo "DEBUG: $ 4 = Root directory for the system: " $4

echo "preinstall: Path to installer....... $1"
echo "preinstall: Path to destination..... $2"
echo "preinstall: Path to dest volume..... $3"
echo "preinstall: Root of system folder... $4"

DEST_VOL="${3}"
EFI_ROOT_DIR="${DEST_VOL}"/Private/tmp/EFIROOTDIR

echo "Fix Audio AppleALC"
if [ -d "${3}/Private/tmp/EFI-DSDT/PackageDIR" ]; then
     echo "File exist Fix Audio AppleALC"
     /usr/libexec/PlistBuddy -c "Set :NVRAM:Add:7C436110-AB2A-4BBB-A880-FE41995C9F82:boot-args keepsyms=1 alcid=13 -v" /Private/tmp/EFIROOTDIR/EFI/OC/config.plist
     Sleep 2
     /usr/libexec/PlistBuddy -c "Merge './Plist-Buddy-Audio' ACPI:Add" /Private/tmp/EFIROOTDIR/EFI/OC/config.plist
     Sleep 1
     cp -Rp ./SSDT-HDEF.aml /Private/tmp/EFIROOTDIR/EFI/OC/ACPI
     echo "Add SSDT-HDEF.aml in /EFI/OC/config.plist"
     echo "Fix Sonoma / Ventura"
elif [ -d "${3}/Private/tmp/EFIROOTDIR/EFI/OC/Kexts/CryptexFixup.kext" ]; then
     echo "File exist Fix Sonoma / Ventura"
     /usr/libexec/PlistBuddy -c "Set :NVRAM:Add:7C436110-AB2A-4BBB-A880-FE41995C9F82:boot-args amfi=0x80 keepsyms=1 alcid=13 -lilubetaall -v" /Volumes/ESP/EFI/OC/config.plist
     
     echo "Change Boot args in /Volumes/ESP/EFI/OC/config.plist"

fi

Sleep 1

echo "Remove install temp files"

if [ -d "${3}/tmp/EFI-DSDT" ]; then
	rm -rf "${3}/tmp/EFI-DSDT"
fi

if [ -d "${3}/tmp/Appli" ]; then
	rm -rf "${3}/tmp/Appli"
fi

rm -rf /"$3"/Private/tmp/EFI

# Remove link to the partition that contain the EFI folder
rm -rf "${DEST_VOL}"/Private/tmp/EFIROOTDIR
rm -rf "${DEST_VOL}"/Private/tmp/EFI

exit